{
 "title": "Grafana Dashboard for Veeam Backup for Nutanix AHV",
 "description": "Grafana Dashboard for Veeam Backup for Nutanix AHV RESTful API. Grafana 7.x",
 "tags": [
  "veeam",
  "nutanix"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "inter",
    "label": "Sampling",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "vanproxy",
    "label": "Veeam Backup AHV Proxy",
    "query": "SHOW TAG VALUES FROM veeam_nutanix_version WITH KEY=vanhostname"
   },
   {
    "name": "veeamserver",
    "label": "Veeam Backup Server",
    "query": "SHOW TAG VALUES FROM veeam_nutanix_server WITH KEY=ServerDescription"
   },
   {
    "name": "repository",
    "label": "Backup Repository",
    "query": "SHOW TAG VALUES FROM veeam_nutanix_repository WITH KEY=repoName"
   },
   {
    "name": "policy",
    "label": "Policy",
    "query": "SHOW TAG VALUES FROM veeam_nutanix_sessions WITH KEY=policyname"
   },
   {
    "name": "ntxcluster",
    "label": "Nutanix Cluster",
    "query": "SHOW TAG VALUES FROM veeam_nutanix_vms WITH KEY=vmcluster"
   },
   {
    "name": "ahvvm",
    "label": "AHV VM",
    "query": "SHOW TAG VALUES FROM veeam_nutanix_vms WITH KEY=vmname"
   },
   {
    "name": "vanversion01",
    "query": "SHOW TAG VALUES FROM veeam_nutanix_version WITH KEY=vanname"
   },
   {
    "name": "vanversion02",
    "query": "SHOW TAG VALUES FROM veeam_nutanix_version WITH KEY=vanversion"
   },
   {
    "name": "vanversion03",
    "query": "SHOW TAG VALUES FROM veeam_nutanix_version WITH KEY=vanoperation"
   },
   {
    "name": "vanversion04",
    "query": "SHOW TAG VALUES FROM veeam_nutanix_version WITH KEY=vandescription"
   },
   {
    "name": "vanversion05",
    "query": "SHOW TAG VALUES FROM veeam_nutanix_version WITH KEY=vanip"
   },
   {
    "name": "vanversion06",
    "query": "SELECT \"vanbuild\" FROM \"veeam_nutanix_version\" WHERE $timeFilter"
   }
  ]
 },
 "panels": [
  {
   "title": "$vanversion01 v$vanversion02 Build $vanversion06 $vanversion04 ($vanversion03) - IP $vanversion05",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "vanproxy"
  },
  {
   "type": "stat",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total VMs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_nutanix_dashboard",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "totalVMsCount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Protected VMs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_nutanix_dashboard",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "protectedVmsCount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Not Protected VMs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_nutanix_dashboard",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "notProtectedVmsCount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Protected VMs with Snapshot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_nutanix_dashboard",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "protectedVmsWithSnapshotsCount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Total Jobs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_nutanix_dashboard",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "totalJobsCount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Total Repositories",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_nutanix_dashboard",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "totalRepositoriesCount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Repo Low in Space",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_nutanix_dashboard",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "repositoriesLowOnSpaceCount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Repo Out of Space",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_nutanix_dashboard",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "repositoriesOutOfSpaceCount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 14, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Backup Server",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_nutanix_dashboard",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "backupServerAvaliability" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Nutanix Cluster",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "veeam_nutanix_dashboard",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "clusterAvaliability" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "VMs Protection Overview",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 1 },
   "format": "short",
   "valueName": "max",
   "targets": [
    {
     "alias": "Protected VMs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_nutanix_dashboard",
     "select": [
      [
       { "params": [ "protectedVmsCount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Unprotected VMs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_nutanix_dashboard",
     "select": [
      [
       { "params": [ "notProtectedVmsCount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Protected VMs Snapshot",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_nutanix_dashboard",
     "select": [
      [
       { "params": [ "protectedVmsWithSnapshotsCount" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Backup Repository - Usage Capacity",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_repoName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT (last(\"repoTotalSpace\") - last(\"repoFreeSpace\")) * (100 / last(\"repoTotalSpace\"))  FROM  \"veeam_nutanix_repository\" WHERE (\"repoName\" =~ /^$repository$/) AND $timeFilter GROUP BY time($__interval), \"repoName\"  fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Job Historical Information",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 8 },
   "targets": [
    {
     "alias": "$tag_policyname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "policyname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_nutanix_sessions",
     "select": [
      [
       { "params": [ "veeamBackupSessionsJobResult" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "policyname", "operator": "=~", "value": "/^$policy$/" }
     ]
    }
   ]
  },
  {
   "title": "$vanversion01 v$vanversion02 Build $vanversion06 $vanversion04 ($vanversion03) - IP $vanversion05 - Policy Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }
  },
  {
   "title": "$policy - Last Result",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 16 },
   "repeat": "policy",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_policyname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "policyname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_nutanix_sessions",
     "query": "SELECT last(\"uptime_latest\") FROM \"vsphere_host_sys\" WHERE (\"esxhostname\" =~ /^$esxi$/ AND \"vcenter\" =~ /^$vcenter$/ AND \"clustername\" =~ /^$clustername$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "veeamBackupSessionsJobResult" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "policyname", "operator": "=~", "value": "/^$policy$/" }
     ]
    }
   ]
  },
  {
   "title": "$vanversion01 v$vanversion02 Build $vanversion06 $vanversion04 ($vanversion03) - IP $vanversion05 - Restore Points per VM (Backup)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "$ahvvm",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 20 },
   "repeat": "ahvvm",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_vmname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "vmname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_nutanix_vms",
     "select": [
      [
       { "params": [ "vmbackups" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$ahvvm$/" },
      { "condition": "AND", "key": "vmcluster", "operator": "=~", "value": "/^$ntxcluster$/" }
     ]
    }
   ]
  },
  {
   "title": "$vanversion01 v$vanversion02 Build $vanversion06 $vanversion04 ($vanversion03) - IP $vanversion05 - Restore Points per VM (Snapshot)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }
  },
  {
   "title": "$ahvvm",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 25 },
   "repeat": "ahvvm",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_vmname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "vmname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_nutanix_vms",
     "select": [
      [
       { "params": [ "vmsnapshots" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "vmname", "operator": "=~", "value": "/^$ahvvm$/" },
      { "condition": "AND", "key": "vmcluster", "operator": "=~", "value": "/^$ntxcluster$/" }
     ]
    }
   ]
  },
  {
   "title": "$vanversion01 v$vanversion02 Build $vanversion06 $vanversion04 ($vanversion03) - IP $vanversion05 - Job Historical Performance and Duration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "repeat": "veeamserver"
  },
  {
   "title": "Policy Performance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_policyname - Bytes read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "policyname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_nutanix_sessions",
     "select": [
      [
       { "params": [ "bytesread" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "policyname", "operator": "=~", "value": "/^$policy$/" }
     ]
    },
    {
     "alias": "$tag_policyname - Bytes transferred",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "policyname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_nutanix_sessions",
     "select": [
      [
       { "params": [ "bytestransferred" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "policyname", "operator": "=~", "value": "/^$policy$/" }
     ]
    }
   ]
  },
  {
   "title": "Job Duration (All type)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "s", "label": "Job Duration" }
   ],
   "targets": [
    {
     "alias": "$tag_policyname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "policyname" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "veeam_nutanix_sessions",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "policyname", "operator": "=~", "value": "/^$policy$/" }
     ]
    }
   ]
  }
 ]
}